services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432

    environment:
       POSTGRES_USER: shivam
       POSTGRES_PASSWORD: shivam1234
       POSTGRES_DB: url-shortner
      
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
 db_data:
